### ISSUE TITLE
Data input - moving around the diva.js image down arrow loses functionality 

### ISSUE THREAD

**Issue by karend27** [MeasuringPolyphony/mp_editor#10]
After you add one or two staves, the down arrow to move down the image doesn't seem to work anymore (also the 'hand' that allows you to reposition the image also is not working). So the only to move the images is with the vertical scroll bar which, as we talked about before, doesn't really work well.

**Comment by JRegimbal** [comment]
The arrow keys are being captured by the staff entry at that point and stop working since that maps to moving an element up or down. As for the hand, that is weird. For me it seems to not work when going to the input screen from the home page, but refreshing it in development mode then causes the dragging to work correctly.

**Comment by karend27** [comment]
The hand is definitely the most intuitive to use, so it would be good to work on having that work all the time. If that's not possible, then could we substitute other actions for the arrows in the staff entry, for example, if you wanted to move a pitch up and down use shift-arrow (instead of just the arrow)? And for text entry, I suggested in another issue that we use space instead of arrow if possible.

**Comment by karend27** [comment]
The hand works when I'm using the mouse, but when I try to just use the trackpad on my laptop it does not work.

**Comment by karend27** [comment]
I'm also going to close this now as I'm happy enough with how moving the diva image is working (using combo of mouse and arrows).
