### ISSUE TITLE
screen 2 enter metadata

### ISSUE THREAD

**Issue by karend27** [MeasuringPolyphony/mp_editor#23]
When I try to type a folio number into the top right box on the diva.js window, I get a popup saying that 'No page could be found with that label or page number', and text in uppercase letters appears in the box (see attached image):
<img width="268" alt="Screen Shot 2020-04-15 at 9 00 58 AM" src="https://user-images.githubusercontent.com/11195203/79340683-adbc2800-7ef8-11ea-98cb-e5bdf66aa47f.png">

**Comment by JRegimbal** [comment]
This is strange. I'm having the same issue but it seems to work if you click on the folio number that appears below the text box. I'll keep looking into this.

**Comment by JRegimbal** [comment]
Oddly enough, it seems that diva replaces the text by searching for the first element with the class name `active`, rather than anything including diva or better yet an element's ID. And since `active` is a fairly generic class name, Angular uses it on the link in the top bar of the screen. I don't totally know what diva is looking for here, but this doesn't seem like good behavior here.

I'm removing the use of `active` as a class outside of diva.
