### ISSUE TITLE
Dots and Ligatures

### ISSUE THREAD

**Issue by DanielS146** [MeasuringPolyphony/mp_editor#56]
In Music Input, it is not possible to add a dot after a note that is in a ligature.

**Comment by martha-thomae** [comment]
This is something that is not supported by Verovio yet. It is also not supported by the MEI schema. I made a [pull request](https://github.com/music-encoding/music-encoding/pull/701) to include this in the schema. I hope it gets accepted soon. After that, maybe @lpugin could take a look at it so that Verovio supports it as well?
