### ISSUE TITLE
Error Moving to Score Editor

### ISSUE THREAD

**Issue by DanielS146** [MeasuringPolyphony/mp_editor#61]
For some reason, I cannot move to Score Editor right now and receive the following error message each time I try.

[Dous amis Console Logs.log](https://github.com/MeasuringPolyphony/mp_editor/files/5130740/Dous.amis.Console.Logs.log)

[Dous amis.zip](https://github.com/MeasuringPolyphony/mp_editor/files/5130708/Dous.amis.zip)

![Dous amis Error Message](https://user-images.githubusercontent.com/69400378/91321686-e2849980-e78c-11ea-936c-16f655a6d1e8.JPG)

**Comment by martha-thomae** [comment]
Ooops, this might be an issue from my part. I am working on something. @JRegimbal could this be because I haven't completed the changes we discussed yesterday for mensur? Are these to be implemented in the development site or in the [https://measuringpolyphony.github.io/mp_editor/](https://measuringpolyphony.github.io/mp_editor/)? @DanielS146, are you using [https://measuringpolyphony.github.io/mp_editor/](https://measuringpolyphony.github.io/mp_editor/)?

If they are related to my thing, I will have it ready in about an hour(?)

**Comment by martha-thomae** [comment]
Apparently, the feature we were working on with Juliette has nothing to do with that. Was it working with that piece before?

**Comment by DanielS146** [comment]
This is a new piece.

**Comment by martha-thomae** [comment]
I think I found the error. Thank you!

**Comment by martha-thomae** [comment]
In theory, is corrected in the new version
